openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: solid-spoon
  url: http://83.212.100.226:3001/v1
security:
- {}
tags:
- description: not yet ready
  name: municipality
paths:
  /municipality:
    post:
      operationId: createmunicipality
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/municipality'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/municipality'
          description: successful operation
      summary: Creates the data
      tags:
      - municipality
      x-eov-operation-handler: controllers/MunicipalityController
  /municipality/{municipalityId}:
    delete:
      operationId: deletemunicipality
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: municipalityId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - municipality
      x-eov-operation-handler: controllers/MunicipalityController
    get:
      operationId: getmunicipality
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: municipalityId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/municipality'
          description: successful operation
      summary: Get the element
      tags:
      - municipality
      x-eov-operation-handler: controllers/MunicipalityController
    put:
      operationId: updatemunicipality
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: municipalityId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/municipality'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/municipality'
          description: successful operation
      summary: Updates the element
      tags:
      - municipality
      x-eov-operation-handler: controllers/MunicipalityController
  /municipality/getAll:
    get:
      operationId: getAllmunicipality
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/municipality'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - municipality
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/MunicipalityController
  /municipality/getByParams/{attribute}/{value}:
    get:
      operationId: getByParamsmunicipality
      parameters:
      - description: the attribute based on which the search is performed
        explode: false
        in: path
        name: attribute
        required: true
        schema:
          type: string
        style: simple
      - description: the value parameter based on which the search is performed
        explode: false
        in: path
        name: value
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/municipality'
                type: array
          description: successful operation
      summary: Get all the data based on user query
      tags:
      - municipality
      x-method-get-by-params: "true"
      x-eov-operation-handler: controllers/MunicipalityController
components:
  schemas:
    municipality:
      example:
        mimage:
          data: data
          name: name
        _id: _id
        mname: mname
      properties:
        _id:
          type: string
        mimage:
          $ref: '#/components/schemas/municipality_mimage'
        mname:
          type: string
      required:
      - mimage
      - mname
      type: object
    municipality_mimage:
      example:
        data: data
        name: name
      properties:
        data:
          type: string
        name:
          type: string
      type: object
      x-isSchemaOnly: "true"
